### ISSUE TITLE
Support for Assuming Roles

### ISSUE THREAD

**Issue by jamesrenaud** [RoadieHQ/backstage-plugin-aws-auth#41]
It would be great to have this plugin support role switching when operating within an AWS organization. It's pretty rare that all your resources are contained within the same AWS account, and I'd like to be able to access other accounts without needing to change the AWS keys available in the keychain for each call.

## Feature Suggestion

For something like the (backstage-plugin-aws-lambda)[https://github.com/RoadieHQ/backstage-plugin-aws-lambda] project, if we could provide a `roleArn` directive to the metadata annotations, and the backend AWS auth would use the default credentials to assume the role before attempting the API call, we'd be able to safely do cross-account AWS API calls.

For example

```
metadata:
  annotations:
    aws.com/role-arn: arn:aws:iam::123456789012:role/Backstage
    aws.com/lambda-function-name: HelloWorld
    aws.com/lambda-region: us-east-1
```

The plugin would use the existing credentials chain available to it, and use the `assumeRole` functionality within `STS` to get temporary credentials to use for the subsequent `getFunctionByName` call.

Extending `generateCredentials` https://github.com/RoadieHQ/backstage-plugin-aws-auth/blob/87a6856244a725179e1c6f18663463ec415cf4ab/src/service/generateTemporaryCredentials.ts#L3 to support an optional role parameter would open this up.
